rm app/models/word.rb
rm app/models/bigimage.rb
rm app/models/language.rb
rm app/models/gameimage.rb
rm app/models/page.rb
rm app/controllers/bigimages_controller.rb
rm app/controllers/gameimages_controller.rb
rm app/controllers/languages_controller.rb
rm app/controllers/words_controller.rb
rm app/controllers/pages_controller.rb
rm db/migrate/*_languages.rb
rm db/migrate/*_words.rb
rm db/migrate/*_gameimages.rb
rm db/migrate/*_bigimages.rb
rm db/migrate/*_pages.rb
rm test/unit/bigimage_test.rb
rm test/unit/gameimage_test.rb
rm test/unit/page_test.rb
rm test/unit/language_test.rb
rm test/unit/word_test.rb